version: '3.8'
services:
  maku-boot:
    image: happy-boot:1.0
    container_name: happy-boot
    ports:
      - 8080:8080
    environment:
      - spring.profiles.active=prod
    volumes:
      - /apps/happy-server.jar:/app/app.jar